const Discord = require("discord.js");
const Client = new Discord.Client();

SecretToken = "insert token here";  // replace this with bot token

/* 
  THIS CODE IS FOR DISPLAY/JOKING PURPOSES ONLY, PLEASE NEVER USE THIS SCRIPT
  JESSE CAN NOT BE HELD RESPONSIBLE FOR ANY PROBLEMS OR ISSUES CAUSED BY THIS PROGRAM

  This bot will create random invite links for Discord, as discord simply uses `discord.gg/` followed by six alpha-numeric characters.
  The code here generates 6 random characters and sends them into your channel every 2.5 seconds.
  Because there are (26*26*10)^6 or 95,428,956,661,680,000,000,000 possible server invite combinations, the odds of this bot guessing one are very low
  Nevertheless, please do not use this code. I made this out of bordem.
  Please never use this code.
*/

Client.login(SecretToken);

Client.on("ready",() => {
  console.log(">>> Invite Finder Online");
  
  Client.guilds.cache.forEach(guild => {
    let channelID;
    let channels = guild.channels;
    channelLoop:
    for(let c of channels){
      let channelType = c[1].type;
      if(channelType === "text"){
        channelID = c[0];
        break channelLoop;
      }
    }

    let channel = bot.channels.get(guild.systemChannelID || channelID);
    channel.send("Hi! I'm the Invite Guesser!\nI randomly generate discord server invite links and send them into a channel.\nThe servers I link probably won't have working links, there are a ton of possible link combinations.\nUse `!!search` and I will begin searching for links every 2.5 seconds in the channel you sent the message\n Use `!!stop` to stop my searching!");
  });
});

var LoopInterval, Searching=false;

Client.on("message",msg => {

  if(msg.content === "!!search"){
    msg.channel.send("Started Searching");

    LoopInterval = setInterval(() => {
    var Gen = GenerateLink();  // creates a new link every loop
    msg.channel.send("discord.gg/"+Gen); // send the random link
    },2500);  // every 2.5 seconds

    Searching = true;
    console.log(">> Started Searching");

  }else if(msg.content === "!!stop"){
  if(Searching === false){
    return msg.channel.send("Not Searching");
  }else if(Searching === true){
    clearInterval(LoopInterval);  // clear the interval, thus stopping the message sending
    Searching = false;
    console.log("> Stopped Searching");
    return msg.channel.send("Stopped Searching");
  }
  }
});

function GenerateLink(){
 var characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"; // a list of all the characters that can be generated by discord link
 var toReturn = ""; // empty string is filled along the way
 var symbols = 6; // how many characters are in a discord link
 for(var count = 0; count < symbols; count++){
  toReturn += characters.charAt(Math.round(Math.random()*characters.length-1));  // add to the empty string a random character from the list
 }
 return toReturn; // return the randomly generated set
}